Algoritmo "Números impar de 100 até 200"
// 
//  The algorithm write the odd numbers from 100 to 200
// Descrição   : algoritmo gera e escreve os números ímpares entre 100 e 200.
// Autor(a)    : João Pedro dos Anjos Martins
// Data atual  : 31/03/2024
Var

i: inteiro

Inicio
escreval ("números impares entre 100 e 200")
i <- 100

para i de 100 ate 200 faca
    se (i mod 2 <> 0) entao
        escreval (i)
    fimse
fimpara

Fimalgoritmo